@startuml School Management System

left to right direction
skinparam linetype polyline

actor "Teacher" as T
actor "Teacher" as TR
actor "Class Teacher" as CT
actor "Class Teacher" as CTR
actor "Sectional Head" as SH
actor "Sectional Head" as SHR
actor "Treasurer" as TS
actor "Treasurer" as TSR
actor "Student" as S
actor "Student" as SR
actor "Prefect" as SP
actor "Prefect" as SPR
actor "Principal" as P
actor "Principal" as PR
actor "Vice Principal" as VP
actor "Vice Principal" as VPR
actor "Administrator" as A
actor "Administrator" as AR
actor "User" as U
actor "User" as UR

U <|-- T
U <|-- S
U <|-- VP
T <|-- CT
T <|-- SH
T <|-- TS
S <|-- SP
VP <|-- P
VP <|-- A

rectangle "School Management System" {
        U -- (Enter the Attendance Daily)
        U -- (Login)
        U -- (Communicate with Users)
        U -- (Logout)

        (Enter the Attendance Daily) ..> (Verify Using Fingerprint) : <<include>>
        (Login) ..> (Validate User) : <<include>>

        T -- (Access Educational Content Dashboard)
        T -- (Access Extracurricular Content Dashboard)
        T -- (Access Students Information)
        T -- (Submit Leave and Short Leaves)

        (Access Educational Content Dashboard) <.. (View Student Activity) : <<extend>>
        (Access Educational Content Dashboard) <.. (Grade Student Activity) : <<extend>>
        (Access Educational Content Dashboard) <.. (Send Feedback and Assessments) : <<extend>>
        (Access Educational Content Dashboard) <.. (Create Educational Content) : <<extend>>
        (Access Educational Content Dashboard) <.. (Update Educational Content) : <<extend>>
        (Access Educational Content Dashboard) <.. (Delete Educational Content) : <<extend>>
        (Access Extracurricular Content Dashboard) <.. (Add Members) : <<extend>>
        (Access Extracurricular Content Dashboard) <.. (Remove Members) : <<extend>>
        (Access Extracurricular Content Dashboard) <.. (Update Members) : <<extend>>
        (Access Extracurricular Content Dashboard) <.. (Create Competitions) : <<extend>>
        (Access Extracurricular Content Dashboard) <.. (Create Societies and Clubs) : <<extend>>
        (Access Extracurricular Content Dashboard) <.. (Monitor Societies and Clubs) : <<extend>>
        (Access Extracurricular Content Dashboard) <.. (Delete Societies and Clubs) : <<extend>>
        (Access Extracurricular Content Dashboard) <.. (Update Societies and Clubs) : <<extend>>
        (Access Students Information) <.. (Update Student Information) : <<extend>>
        (Access Students Information) <.. (Delete Student Information) : <<extend>>
        (Access Students Information) <.. (Create Student Information) : <<extend>>
        (Access Students Information) <.. (View Student Progress and Performance) : <<extend>>
        (Submit Leave and Short Leaves) ..> (Verify Leave) : <<include>>
        
        CT -- (View Students Attendance)
        CT -- (View Exam Results)
        CT -- (Generate Student Reports)

        (View Students Attendance) <.. (Generate Student Attendence Reports) : <<extend>>
        (View Exam Results) <.. (Enter Exam Results) : <<extend>>
        (View Exam Results) <.. (Update Exam Results) : <<extend>>
        (View Exam Results) <.. (Remove Exam Results) : <<extend>>
        (View Exam Results) <.. (Sort Student Marks) : <<extend>>
        (Generate Student Reports) ..> (Inform Class Students) : <<include>>

        SH -- (Schedule Sectional Staff Meetings)
        SH -- (Create Sectional Events)

        (Schedule Sectional Staff Meetings) ..> (Inform Sectional Teachers) : <<include>>
        (Create Sectional Events) ..> (Inform Sectional Teachers) : <<include>>
        (Create Sectional Events) ..> (Inform Sectional Students) : <<include>>
        
        TS -- (View School Financial Status)
        TS -- (Withdraw Funds from School Account)
        TS -- (Deposit Funds to School Account)
        TS -- (Monitor Student Payments)

        (View School Financial Status) <.. (Generate Financial Reports) : <<extend>>
        (View School Financial Status) <.. (Calculate School Budget) : <<extend>>
        (View School Financial Status) <.. (Monitor Student Payment) : <<extend>>
        (Monitor Student Payments) <.. (Notify Students) : <<extend>>
        (Withdraw Funds from School Account) ..> (Request Principal Permission) : <<include>>
        (Withdraw Funds from School Account) ..> (Update Logs) : <<include>>
        (Deposit Funds to School Account) ..> (Update Logs) : <<include>>

        S -- (Access Educational Content Dashboard as a Student)
        S -- (Access Extracurricular Content Dashboard as a Student)
        S -- (Pay School Fees and Other Welfare Fees)
        S -- (Submit Medicals for Sudden Leaves)
        S -- (Create School Societies and Clubs)

        (Access Educational Content Dashboard as a Student) <.. (View Educational Content) : <<extend>>
        (Access Educational Content Dashboard as a Student) <.. (View Assessments) : <<extend>>
        (Access Educational Content Dashboard as a Student) <.. (Submit Assessments) : <<extend>>
        (Access Educational Content Dashboard as a Student) <.. (Update Assessments) : <<extend>>
        (Access Extracurricular Content Dashboard as a Student) <.. (Apply for Societies and Clubs) : <<extend>>
        (Access Extracurricular Content Dashboard as a Student) <.. (Apply for Competitions) : <<extend>>
        (Pay School Fees and Other Welfare Fees) ..> (Generate Receipts) : <<include>>
        (Submit Medicals for Sudden Leaves) ..> (Verify Medical Information) : <<include>>

        SP -- (Enter Student Information as a Prefect)
        SP -- (Create Events for Students)
        SP -- (Delete Events for Students)
        SP -- (Update Events for Students)

        (Enter Student Information as a Prefect) <.. (Update Student Information as a Prefect) <<extend>>
        (Create Events for Students) ..> (Inform Students as a Prefect) : <<include>>
        (Delete Events for Students) ..> (Inform Students as a Prefect) : <<include>>
        (Update Events for Students) ..> (Inform Students as a Prefect) : <<include>> 

        VP -- (View Staff Members)
        VP -- (View Student Enrollment)
        VP -- (View Administrative Tasks)
        VP -- (Broadcast Announcements)

        (View Staff Members) <.. (Schedule Staff Meetings) : <<extend>>
        (View Staff Members) <.. (Add Staff Members) : <<extend>>
        (View Staff Members) <.. (Remove Staff Members) : <<extend>>
        (View Staff Members) <.. (Update Staff Members) : <<extend>>
        (View Student Enrollment) <.. (Review Enrollment Data) : <<extend>>
        (View Student Enrollment) <.. (Generate Enrollment Reports) : <<extend>>
        (View Administrative Tasks) <.. (Edit Administrative Tasks) : <<extend>>
        (View Administrative Tasks) <.. (Update Administrative Tasks) : <<extend>>
        (View Administrative Tasks) <.. (Delete Administrative Tasks) : <<extend>>
        (View Administrative Tasks) <.. (Create Administrative Tasks) : <<extend>>
        
        P -- (Generate Reports)
        P -- (Create Special School Events)

        (Generate Reports) <.. (User Engagement Reports) : <<extend>>
        (Generate Reports) <.. (Performance Reports) : <<extend>>
        (Generate Reports) <.. (System Utilization Reports) : <<extend>>
        (Generate Reports) <.. (Content Popularity Reports) : <<extend>>
        (Generate Reports) <.. (Monthly Attendance Reports) : <<extend>>
        (Create Special School Events) ..> (Inform Teachers as the Principal) : <<include>>
        (Create Special School Events) ..> (Inform Students as the Principal) : <<include>>

        A -- (Create User Accounts and Access Permissions)
        A -- (Oversee Overall Functionality and Performance)
        A -- (Ensure Security and Integrity of the Platform)

        (Create User Accounts and Access Permissions) <.. (Add User) : <<extend>>
        (Create User Accounts and Access Permissions) <.. (Delete User) : <<extend>>
        (Create User Accounts and Access Permissions) <.. (Modify Permissions) : <<extend>>
        (Oversee Overall Functionality and Performance) ..> (Oversee School Management) : <<include>>
        (Ensure Security and Integrity of the Platform) <.. (Encrypt Data) : <<extend>>
        (Ensure Security and Integrity of the Platform) <.. (Regular Data Backups) : <<extend>>
}

@enduml