@startuml School Management System

actor "Student" as S
boundary "School Management System" as SMS
control "Payment" as P
entity "Finance" as F
actor "Teacher" as T

S -> SMS: View Payment Information
activate SMS
SMS --> S: Display payment information
SMS -> P: Pay School Fees
activate P
P --> S: Confirmation message
S --> P: Confirmation
P --> F: Update Payment Information
activate F
P --> S: Payment Complete
deactivate P
F --> T: View Payment Update
deactivate F

SMS -> P: Pay Welfare Fees
activate P
P --> S: Confirmation message
S --> P: Confirmation
P --> F: Update Payment Information
activate F
F --> T: View Payment Update
deactivate F
P --> S: Confirmation message
deactivate P

SMS -> P: Donate to the School
activate P
P --> S: Confirmation message
S --> P: Confirmation
P --> F: Update Payment Information
activate F
F --> T: View Payment Update
deactivate F
P --> S: Confirmation message
deactivate P

@enduml