@startuml School Management System

left to right direction
skinparam linetype polyline

actor "Teacher" as T
actor "Teacher" as TR
actor "Class Teacher" as CT
actor "Class Teacher" as CTR
actor "Sectional Head" as SH
actor "Sectional Head" as SHR
actor "Treasurer" as TS
actor "Treasurer" as TSR
actor "Student" as S
actor "Student" as SR
actor "Prefect" as SP
actor "Prefect" as SPR
actor "Principal" as P
actor "Principal" as PR
actor "Vice Principal" as VP
actor "Vice Principal" as VPR
actor "Administrator" as A
actor "Administrator" as AR
actor "User" as U
actor "User" as UR

U <|-- T
U <|-- S
U <|-- VP
T <|-- CT
T <|-- SH
T <|-- TS
S <|-- SP
VP <|-- P
VP <|-- A

rectangle "School Management System" {
        U -- (Enter the Attendance Daily)
        (Enter the Attendance Daily) ..> (Verify Using Fingerprint) : <<include>>

        U -- (Login)
        (Login) ..> (Validate User) : <<include>>

        U -- (Access User Profile)
        (Access User Profile) <.. (View User Information) : <<extend>>
        (Access User Profile) <.. (Update User Profile) : <<extend>>

        U -- (Communicate with Users)
        (Communicate with Users) ..> (Send Messages to Users) : <<include>>
        (Send Messages to Users) -- UR

        U -- (Logout)

        T -- (Access Educational Content Dashboard)
        (Access Educational Content Dashboard) <.. (View Student Activity) : <<extend>>
        (Access Educational Content Dashboard) <.. (Grade Student Activity) : <<extend>>
        (Access Educational Content Dashboard) <.. (Send Feedback and Assessments) : <<extend>>
        (Access Educational Content Dashboard) <.. (Create Educational Content) : <<extend>>
        (Access Educational Content Dashboard) <.. (Update Educational Content) : <<extend>>
        (Access Educational Content Dashboard) <.. (Delete Educational Content) : <<extend>>

        T -- (Access Extracurricular Content Dashboard)
         (Access Extracurricular Content Dashboard) <.. (Add Members) : <<extend>>
        (Access Extracurricular Content Dashboard) <.. (Remove Members) : <<extend>>
        (Access Extracurricular Content Dashboard) <.. (Update Members) : <<extend>>
        (Access Extracurricular Content Dashboard) <.. (Create Competitions) : <<extend>>
        (Access Extracurricular Content Dashboard) <.. (Create Societies and Clubs) : <<extend>>
        (Access Extracurricular Content Dashboard) <.. (Monitor Societies and Clubs) : <<extend>>
        (Access Extracurricular Content Dashboard) <.. (Delete Societies and Clubs) : <<extend>>
        (Access Extracurricular Content Dashboard) <.. (Update Societies and Clubs) : <<extend>>

        T -- (Access Students Information)
        (Access Students Information) <.. (Update Student Information) : <<extend>>
        (Access Students Information) <.. (Delete Student Information) : <<extend>>
        (Access Students Information) <.. (Create Student Information) : <<extend>>
        (Access Students Information) <.. (View Student Performance) : <<extend>>
        (Access Students Information) <.. (Update Student Performance) : <<extend>>
        (Access Students Information) <.. (View Student Attendance) : <<extend>>

        T -- (Access Exam Information)
        (Access Exam Information) <.. (Enter Exam Results) : <<extend>>
        (Access Exam Information) <.. (Update Exam Results) : <<extend>>
        (Access Exam Information) <.. (Remove Exam Results) : <<extend>>
        (Access Exam Information) <.. (Sort Student Marks) : <<extend>>
        
        T -- (Submit Leaves and Short Leaves)
        (Submit Leaves and Short Leaves) ..> (Request Permission) : <<include>>

        CT -- (Generate Student Reports)
        (Generate Student Reports) <.. (Attendance Reports) : <<extend>>
        (Generate Student Reports) <.. (Performance Reports) : <<extend>>
        (Generate Student Reports) <.. (Attendance Reports) : <<extend>>

        SH -- (Schedule Sectional Staff Meetings)
        (Schedule Sectional Staff Meetings) ..> (Inform Sectional Teachers) : <<include>>

        SH -- (Access Event Management Dashboard)
        (Access Event Management Dashboard) <.. (Create Sectional Events) : <<extend>>
        (Access Event Management Dashboard) <.. (Update Sectional Events) : <<extend>>
        (Access Event Management Dashboard) <.. (Delete Sectional Events) : <<extend>>

        SH -- (Generate Reports)
        (Generate Reports) <.. (User Engagement Reports) : <<extend>>
        (Generate Reports) <.. (Performance Reports) : <<extend>>
        (Generate Reports) <.. (System Utilization Reports) : <<extend>>
        (Generate Reports) <.. (Content Popularity Reports) : <<extend>>
        (Generate Reports) <.. (Monthly Attendance Reports) : <<extend>>
        
        TS -- (View School Financial Status)
        (View School Financial Status) <.. (Generate Financial Reports) : <<extend>>
        (View School Financial Status) <.. (Calculate School Budget) : <<extend>>
        (View School Financial Status) <.. (Monitor Student Payment) : <<extend>>

        TS -- (Withdraw Funds from School Account)
        (Withdraw Funds from School Account) ..> (Request Principal Permission) : <<include>>
        (Withdraw Funds from School Account) ..> (Update Logs) : <<include>>

        TS -- (Deposit Funds to School Account)
        (Deposit Funds to School Account) ..> (Update Logs) : <<include>>

        TS -- (Monitor Student Payments)
        (Monitor Student Payments) <.. (Notify Students) : <<extend>>

        S -- (Access Educational Content Dashboard as a Student)
        (Access Educational Content Dashboard as a Student) <.. (View Educational Content) : <<extend>>
        (Access Educational Content Dashboard as a Student) <.. (View Assessments) : <<extend>>
        (Access Educational Content Dashboard as a Student) <.. (Submit Assessments) : <<extend>>
        (Access Educational Content Dashboard as a Student) <.. (Update Assessments) : <<extend>>

        S -- (Access Extracurricular Content Dashboard as a Student)
        (Access Extracurricular Content Dashboard as a Student) <.. (Apply for Societies and Clubs) : <<extend>>
        (Access Extracurricular Content Dashboard as a Student) <.. (Apply for Competitions) : <<extend>>

        S -- (Pay School Fees and Other Welfare Fees)
        (Pay School Fees and Other Welfare Fees) ..> (Generate Receipts) : <<include>>

        S -- (Submit Queries)
        (Submit Queries) <.. (Medicals for Sudden Leaves) : <<extend>>
        (Submit Queries) <.. (Parent Letters) : <<extend>>

        SP -- (Access Student Information as a Prefect)
        (Access Student Information as a Prefect) <.. (Update disciplinary Status) : <<extend>>

        SP -- (Access Event Management Dashboard as a Prefect)
        (Access Event Management Dashboard as a Prefect) <.. (Create Events for Students) : <<extend>>
        (Access Event Management Dashboard as a Prefect) <.. (Delete Events for Students) : <<extend>>
        (Access Event Management Dashboard as a Prefect) <.. (Update Events for Students) : <<extend>>

        VP -- (Access Staff Management Dashboard)
        (Access Staff Management Dashboard) <.. (Schedule Staff Meetings) : <<extend>>
        (Access Staff Management Dashboard) <.. (Add Staff Members) : <<extend>>
        (Access Staff Management Dashboard) <.. (Remove Staff Members) : <<extend>>
        (Access Staff Management Dashboard) <.. (Update Staff Members) : <<extend>>

        VP -- (Access Student Management Dashboard)
        (Access Student Management Dashboard) <.. (Review Enrollment Information) : <<extend>>
        (Access Student Management Dashboard) <.. (Generate Enrollment Reports) : <<extend>>

        VP -- (Access Administrative Management Dashboard)
        (Access Administrative Management Dashboard) <.. (Edit Administrative Content) : <<extend>>
        (Access Administrative Management Dashboard) <.. (Update Administrative Content) : <<extend>>
        (Access Administrative Management Dashboard) <.. (Delete Administrative Content) : <<extend>>
        (Access Administrative Management Dashboard) <.. (Create Administrative Content) : <<extend>>

        VP -- (Broadcast Announcements)
        (Broadcast Announcements) ..> (Send Notifications to Users) : <<include>>
        (Send Notifications to Users) -- UR

        P -- (Create Special School Events)
        (Create Special School Events) ..> (Inform Teachers as the Principal) : <<include>>
        (Create Special School Events) ..> (Inform Students as the Principal) : <<include>>

        A -- (Create User Accounts and Access Permissions)
        (Create User Accounts and Access Permissions) <.. (Add User) : <<extend>>
        (Create User Accounts and Access Permissions) <.. (Delete User) : <<extend>>
        (Create User Accounts and Access Permissions) <.. (Modify Permissions) : <<extend>>

        A -- (Oversee Overall Functionality and Performance)
        (Oversee Overall Functionality and Performance) <.. (Oversee School Management) : <<extend>>
        (Oversee Overall Functionality and Performance) <.. (View School Staticstics) : <<extend>>

        A -- (Ensure Security and Integrity of the Platform)
        (Ensure Security and Integrity of the Platform) <.. (Encrypt Data) : <<extend>>
        (Ensure Security and Integrity of the Platform) <.. (Regular Data Backups) : <<extend>>
}

@enduml