@startuml School Management System

left to right direction
skinparam linetype polyline

actor "Teacher" as T
actor "Teacher" as TR
actor "Teacher" as TR2
actor "Sectional Head" as SH
actor "Sectional Head" as SHR
actor "Student" as S
actor "Student" as SR
actor "Principal" as P
actor "Principal" as PR
actor "Vice Principal" as VP
actor "Vice Principal" as VPR
actor "Administrator" as A
actor "User" as U
actor "User" as UR

U <|-- S
S <|-- T
T <|-- SH
SH <|-- VP
VP <|-- P
P <|-- A

rectangle "School Management System" {
        A -- (Access User Management Dashboard)
        (Access User Management Dashboard) <.. (Add User) : <<extend>>
        (Access User Management Dashboard) <.. (Delete User) : <<extend>>
        (Access User Management Dashboard) <.. (Modify Permissions) : <<extend>>
        
        (Add User) ..> (Update Registration Records) : <<include>>
        (Delete User) ..> (Update Registration Records) : <<include>>
        (Modify Permissions) ..> (Update Registration Records) : <<include>>

        A -- (Access System Monitor)
        (Access System Monitor) <.. (View System Staticstics) : <<extend>>
        (Access System Monitor) <.. (Generate User Engagement Reports) : <<extend>>
        (Access System Monitor) <.. (Generate Performance Reports) : <<extend>>
        (Access System Monitor) <.. (Generate System Utilization Reports) : <<extend>>
        (Access System Monitor) <.. (Generate Content Popularity Reports) : <<extend>>
        (Access System Monitor) <.. (Generate Monthly Attendance Reports) : <<extend>>
        (Access System Monitor) <.. (Encrypt Data) : <<extend>>
        (Access System Monitor) <.. (Regular Data Backups) : <<extend>>
        
        (Generate User Engagement Reports) ..> (Inform Vice Principal) : <<include>>
        (Generate Performance Reports) ..> (Inform Vice Principal) : <<include>>
        (Generate System Utilization Reports) ..> (Inform Vice Principal) : <<include>>
        (Generate Content Popularity Reports) ..> (Inform Vice Principal) : <<include>>
        (Generate Monthly Attendance Reports) ..> (Inform Vice Principal) : <<include>>

        A -- (Access System Database)
        (Access System Database) <.. (Create Tables) : <<extend>>
        (Access System Database) <.. (Remove Tables) : <<extend>>
        (Access System Database) <.. (Update Tables) : <<extend>>
        (Access System Database) <.. (Delete Tables) : <<extend>>

        P -- (Access Administrative Dashboard)
        (Access Administrative Dashboard) <.. (View Policies) : <<extend>>
        (Access Administrative Dashboard) <.. (Create Policies) : <<extend>>
        (Access Administrative Dashboard) <.. (Update Policies) : <<extend>>
        (Access Administrative Dashboard) <.. (Delete Policies) : <<extend>>

        (Create Policies) ..> (Inform Vice Principal): <<include>>
        (Create Policies) ..> (Inform Sectional Heads): <<include>>
        (Update Policies) ..> (Inform Vice Principal): <<include>>
        (Delete Policies) ..> (Inform Vice Principal): <<include>>

        (Inform Principal) -- PR

        VP -- (Broadcast Announcements)
        (Broadcast Announcements) ..> (Send Messages as the Principal) : <<include>>
        (Send Messages as the Principal) ..> (Inform Sectional Heads) : <<include>>

        VP -- (Access Event Management Dashboard)
        (Access Event Management Dashboard) <.. (Create Events) : <<extend>>
        (Access Event Management Dashboard) <.. (Update Events) : <<extend>>
        (Access Event Management Dashboard) <.. (Delete Events) : <<extend>>

        (Create Events) ..> (Inform Sectional Heads): <<include>>
        (Update Events) ..> (Inform Sectional Heads): <<include>>
        (Delete Events) ..> (Inform Sectional Heads): <<include>>

        VP -- (Access Staff Management Dashboard)
        (Access Staff Management Dashboard) <.. (Schedule Meetings) : <<extend>>
        (Access Staff Management Dashboard) <.. (Add Staff Members) : <<extend>>
        (Access Staff Management Dashboard) <.. (Remove Staff Members) : <<extend>>
        (Access Staff Management Dashboard) <.. (Update Staff Members) : <<extend>>

        (Schedule Meetings) ..> (Inform Sectional Heads) : <<include>>
        (Update Staff Members) ..> (Inform Sectional Heads): <<include>>

        VP -- (Access Student Management Dashboard)
        (Access Student Management Dashboard) <.. (view Enrollment Information) : <<extend>>
        (Access Student Management Dashboard) <.. (Generate Enrollment Reports) : <<extend>>

        (Generate Enrollment Reports) ..> (Inform Principal): <<include>>

        VP -- (Access Financial Management Dashboard)
        (Access Financial Management Dashboard) <.. (Monitor Student Payments) : <<extend>>
        (Access Financial Management Dashboard) <.. (View School Budget) : <<extend>>
        (Access Financial Management Dashboard) <.. (Plan School Budget) : <<extend>>
        (Access Financial Management Dashboard) <.. (Update School Budget) : <<extend>>

        (Plan School Budget) ..> (Inform Principal): <<include>>
        (Update School Budget) ..> (Inform Principal): <<include>>
        
        (Access Financial Management Dashboard) <.. (Generate Financial Reports) : <<extend>>
        (Access Financial Management Dashboard) <.. (Withdraw Funds from School Account) : <<extend>>
        (Access Financial Management Dashboard) <.. (Deposit Funds to School Account) : <<extend>>

        (Withdraw Funds from School Account) ..> (Inform Principal) : <<include>>
        (Deposit Funds to School Account) ..> (Inform Principal) : <<include>>

        (Inform Vice Principal) -- VPR
        (Update Registration Records) -- VPR

        SH -- (Access Exams Management Dashboard)
        (Access Exams Management Dashboard) <.. (Create Exams) : <<extend>>
        (Access Exams Management Dashboard) <.. (Update Exams) : <<extend>>
        (Access Exams Management Dashboard) <.. (Delete Exams) : <<extend>>

        (Create Exams) ..> (Inform Teachers): <<include>>
        (Update Exams) ..> (Inform Teachers): <<include>>
        (Delete Exams) ..> (Inform Teachers): <<include>>

        SH -- (Access Staff Management Dashboard as a Teacher)
        (Access Staff Management Dashboard as a Teacher) <.. (Schedule Sectional Staff Meetings) : <<extend>>
        (Access Staff Management Dashboard as a Teacher) <.. (Create Time Tables) : <<extend>>
        (Access Staff Management Dashboard as a Teacher) <.. (Update Time Tables) : <<extend>>
        (Access Staff Management Dashboard as a Teacher) <.. (Delete Time Tables) : <<extend>>
        
        (Schedule Sectional Staff Meetings) ..> (Inform Teachers) : <<include>>
        (Create Time Tables) ..> (Inform Teachers): <<include>>
        (Update Time Tables) ..> (Inform Teachers) : <<include>>
        
        (Inform Sectional Heads) -- SHR

        T -- (Access Educational Content Dashboard)
        (Access Educational Content Dashboard) <.. (View Student Activity) : <<extend>>
        (Access Educational Content Dashboard) <.. (Grade Student Activity) : <<extend>>
        (Access Educational Content Dashboard) <.. (Send Feedback and Assessments) : <<extend>>
        (Access Educational Content Dashboard) <.. (Create Educational Content) : <<extend>>
        (Access Educational Content Dashboard) <.. (Update Educational Content) : <<extend>>
        (Access Educational Content Dashboard) <.. (Delete Educational Content) : <<extend>>
        (Access Educational Content Dashboard) <.. (View Time Table) : <<extend>>

        (Grade Student Activity) ..> (Notify Students): <<include>>
        (Send Feedback and Assessments) ..> (Notify Students): <<include>>
        (Create Educational Content) ..> (Notify Students): <<include>>
        (Update Educational Content) ..> (Notify Students): <<include>>
        (Delete Educational Content) ..> (Notify Students): <<include>>

        T -- (Access Extracurricular Content Dashboard)
        (Access Extracurricular Content Dashboard) <.. (Add Members) : <<extend>>
        (Access Extracurricular Content Dashboard) <.. (Remove Members) : <<extend>>
        (Access Extracurricular Content Dashboard) <.. (Update Members) : <<extend>>
        (Access Extracurricular Content Dashboard) <.. (Create Competitions) : <<extend>>
        (Access Extracurricular Content Dashboard) <.. (Create Societies and Clubs) : <<extend>>
        (Access Extracurricular Content Dashboard) <.. (Monitor Societies and Clubs) : <<extend>>
        (Access Extracurricular Content Dashboard) <.. (Delete Societies and Clubs) : <<extend>>
        (Access Extracurricular Content Dashboard) <.. (Update Societies and Clubs) : <<extend>>

        (Add Members) ..> (Notify Students): <<include>>
        (Remove Members) ..> (Notify Students): <<include>>
        (Update Members) ..> (Notify Students): <<include>>
        (Create Competitions) ..> (Notify Students): <<include>>
        (Create Societies and Clubs) ..> (Notify Students): <<include>>
        (Update Societies and Clubs) ..> (Notify Students): <<include>>

        T -- (Access Students Management Dashboard as a Teacher)
        (Access Students Management Dashboard as a Teacher) <.. (Update Student Information) : <<extend>>
        (Access Students Management Dashboard as a Teacher) <.. (Delete Student Information) : <<extend>>
        (Access Students Management Dashboard as a Teacher) <.. (Create Student Information) : <<extend>>
        (Access Students Management Dashboard as a Teacher) <.. (View Student Performance) : <<extend>>
        (Access Students Management Dashboard as a Teacher) <.. (Generate Student Performance Reports) : <<extend>>
        (Access Students Management Dashboard as a Teacher) <.. (Update Student Performance) : <<extend>>
        (Access Students Management Dashboard as a Teacher) <.. (View Student Attendance) : <<extend>>
        (Access Students Management Dashboard as a Teacher) <.. (Generate Student Attendance Reports) : <<extend>>

        (Generate Student Performance Reports) ..> (Notify Students) : <<include>>
        (Generate Student Attendance Reports) ..> (Notify Students) : <<include>>

        T -- (Access Exam Dashboard as a Teacher)
        (Access Exam Dashboard as a Teacher) <.. (View Exam Results) : <<extend>>
        (Access Exam Dashboard as a Teacher) <.. (Enter Exam Results) : <<extend>>
        (Access Exam Dashboard as a Teacher) <.. (Update Exam Results) : <<extend>>
        (Access Exam Dashboard as a Teacher) <.. (Delete Exams Results) : <<extend>>

        (Enter Exam Results) ..> (Notify Students): <<include>>
        (Update Exam Results) ..> (Notify Students): <<include>>
        
        T -- (Access Query Dashboard)
        (Access Query Dashboard) <.. (Submit Leaves and Short Leaves) : <<extend>>
        (Access Query Dashboard) <.. (View Student Queries) : <<extend>>
        (Access Query Dashboard) <.. (Feedback Student Queries) : <<extend>>

        (Submit Leaves and Short Leaves) ..> (Notify Students) : <<include>>
        (Feedback Student Queries) ..> (Notify Students): <<include>>
        
        (Update Financial Information) -- TR
        (Update Logs) -- TR
        (Notify Teachers) -- TR
        (Inform Teachers) -- TR2

        S -- (Access Query Dashboard as a Student)
        (Access Query Dashboard as a Student) <.. (Submit Queries as a Student) : <<extend>>
        (Access Query Dashboard as a Student) <.. (Submit Queries as a Parent) : <<extend>>
        (Access Query Dashboard as a Student) <.. (Submit Queries as a Guardian) : <<extend>>

        (Submit Queries as a Student) ..> (Notify Teachers) : <<include>>
        (Submit Queries as a Parent) ..> (Notify Teachers) : <<include>>
        (Submit Queries as a Guardian) ..> (Notify Teachers) : <<include>>

        S -- (Access Educational Content Dashboard as a Student)
        (Access Educational Content Dashboard as a Student) <.. (View Educational Content) : <<extend>>
        (Access Educational Content Dashboard as a Student) <.. (View Assessments) : <<extend>>
        (Access Educational Content Dashboard as a Student) <.. (Submit Assessments) : <<extend>>
        (Access Educational Content Dashboard as a Student) <.. (Update Assessments) : <<extend>>
        (Access Educational Content Dashboard as a Student) <.. (View Time Tables) : <<extend>>

        (Submit Assessments) ..> (Notify Teachers): <<include>>
        (Update Assessments) ..> (Notify Teachers): <<include>>

        S -- (Access Extracurricular Content Dashboard as a Student)
        (Access Extracurricular Content Dashboard as a Student) <.. (Apply for Societies and Clubs) : <<extend>>
        (Access Extracurricular Content Dashboard as a Student) <.. (Apply for Competitions) : <<extend>>

        (Apply for Societies and Clubs) ..> (Notify Teachers): <<include>>
        (Apply for Competitions) ..> (Notify Teachers): <<include>>

        S -- (Access Exam Dashboard as a Student)
        (Access Exam Dashboard as a Student) <.. (View Exams as a Student) : <<extend>>
        (Access Exam Dashboard as a Student) <.. (View Exam Results as a Student) : <<extend>>

        S -- (Access Payment Dashboard)
        (Access Payment Dashboard) <.. (Pay School Fees) : <<extend>>
        (Access Payment Dashboard) <.. (Pay Welfare Fees) : <<extend>>
        (Access Payment Dashboard) <.. (Donate to the School) : <<extend>>

        (Pay School Fees) ..> (Update Financial Information) : <<include>>
        (Pay Welfare Fees) ..> (Update Financial Information) : <<include>>
        (Donate to the School) ..> (Update Financial Information) : <<include>>
        
        (Notify Students) -- SR

        U -- (Enter the Attendance Daily)
        (Enter the Attendance Daily) ..> (Verify Using Fingerprint) : <<include>>

        U -- (Login)
        (Login) ..> (Validate User) : <<include>>
        (Validate User)..> (Update Logs) : <<include>>


        U -- (Access User Profile)
        (Access User Profile) <.. (View User Information) : <<extend>>
        (Access User Profile) <.. (Update User Profile) : <<extend>>

        U -- (Comminication)
        (Comminication) <.. (Send Messages) : <<extend>>

        (Send Messages) ..> (Notify Users) : <<include>>

        U -- (Logout)
        (Logout) ..> (Confirm) : <<include>>

        (Notify Users) -- UR
}

@enduml