@startuml School Management System
title School Management System - Proposed Use Case Diagram

left to right direction
skinparam linetype polyline

actor "User" as U
actor "User" as UR
actor "Student" as S
actor "Student" as SR
actor "Teacher" as T
actor "Teacher" as TR
actor "Sectional Head" as SH
actor "Sectional Head" as SHR
actor "Principal" as P
actor "Principal" as PR
actor "Administrator" as A

U <|-- S
U <|-- T
T <|-- SH
SH <|-- P
P <|-- A

rectangle "School Management System" {
        U -- (Enter the Attendance Daily)
        (Enter the Attendance Daily) ..> (Verify Using Fingerprint) : <<include>>
        (Verify Using Fingerprint) ..> (Update User Log) : <<include>>

        U -- (Login)
        (Login) ..> (Validate User) : <<include>>
        (Validate User) ..> (Update User Log) : <<include>>

        U -- (View User Profile)
        (View User Profile) <.. (Update User Profile) : <<extends>>
        (Update User Profile) ..> (Update User Log) : <<include>>

        U -- (Communication)
        (Communication) <.. (Send Messages) : <<extends>>
        (Send Messages) ..> (Update User Log) : <<include>>

        U -- (Logout)
        (Logout) ..> (Confirm) : <<include>>
        (Confirm) ..> (Update User Log) : <<include>>

        (Notify Users) -- UR

        S -- (View Educational Information)
        (View Educational Information) <.. (Submit Assessments) : <<extends>>
        (View Educational Information) <.. (View Assessments) : <<extends>>

        (Submit Assessments) ..> (Update Educational Information) : <<include>>
        (View Assessments) ..> (View Submission Marks) : <<include>>

        S -- (View Exams Information)
        (View Exams Information) <.. (View Exams) : <<extends>>
        (View Exams Information) <.. (View Exam Results) : <<extends>>
        (View Exam Results) <.. (Apply for Recorrections) : <<extends>>
        (View Exam Results) <.. (Calculate GPA) : <<extends>>

        (Update Student Information ) -- SR
        (Update Educational Information ) -- SR
        (Update Exam Information ) -- SR

        T -- (View Student Information )
        (View Student Information ) <.. (Create Student Information ) : <<extends>>
        (View Student Information ) <.. (Delete Student Information ) : <<extends>>
        (View Student Information ) <.. (Generate Student Attendance Reports) : <<extends>>
        (View Student Information ) <.. (Generate Student Performance Reports) : <<extends>>
        (View Student Information ) <.. (Generate Enrollment Reports) : <<extends>>

        (Create Student Information ) ..> (Update Student Information ) : <<include>>
        (Delete Student Information ) ..> (Update Student Information ) : <<include>>
        (Generate Student Attendance Reports) ..> (Update Student Information ) : <<include>>
        (Generate Student Performance Reports) ..> (Update Student Information ) : <<include>>
        (Generate Enrollment Reports) ..> (Update Student Information ): <<include>>

        T -- (View Educational Information )
        (View Educational Information ) <.. (Create Assessments) : <<extends>>
        (View Educational Information ) <.. (Edit Assessments) : <<extends>>
        (View Educational Information ) <.. (Delete Assessments) : <<extends>>

        T -- (View Student Submissions)
        (View Student Submissions) <.. (Mark Student Submissions) : <<extends>>

        (Create Assessments) ..> (Update Educational Information ): <<include>>
        (Edit Assessments) ..> (Update Educational Information ): <<include>>
        (Delete Assessments) ..> (Update Educational Information ): <<include>>
        (Mark Student Submissions) ..> (Update Educational Information ) : <<include>>

        T -- (View Exam Information )
        (View Exam Information ) <.. (Create Exams) : <<extends>>
        (View Exam Information ) <.. (Update Exams) : <<extends>>
        (View Exam Information ) <.. (Delete Exams) : <<extends>>
        (View Exam Information ) <.. (Edit Exam Results) : <<extends>>

        (Create Exams) ..> (Update Exam Information ) : <<include>>
        (Update Exams) ..> (Update Exam Information ) : <<include>>
        (Delete Exams) ..> (Update Exam Information ) : <<include>>
        (Edit Exam Results) ..> (Update Exam Information ) : <<include>>

        (Update Educational Information) -- TR
        (Apply for Recorrections) -- TR
        (Notify Teachers) -- TR

        SH -- (View Staff Information )
        (View Staff Information ) <.. (Add Staff Members) : <<extends>>
        (View Staff Information ) <.. (Update Staff Members) : <<extends>>
        (View Staff Information ) <.. (Remove Staff Members) : <<extends>>
        
        SH -- (View Sectional Information )
        (View Sectional Information ) <.. (Create Time Tables) : <<extends>>
        (View Sectional Information ) <.. (Update Time Tables) : <<extends>>
        (View Sectional Information ) <.. (Delete Time Tables) : <<extends>>

        (Notify Sectional Heads) -- SHR

        (Add Staff Members) ..> (Notify Teachers) : <<include>>
        (Update Staff Members) ..> (Notify Teachers) : <<include>>
        (Remove Staff Members) ..> (Notify Teachers) : <<include>>
        (Create Time Tables) ..> (Notify Teachers): <<include>>
        (Update Time Tables) ..> (Notify Teachers) : <<include>>
        (Delete Time Tables) ..> (Notify Teachers) : <<include>>

        P -- (Broadcast Announcements)
        (Broadcast Announcements) ..> (Select Users) : <<include>>

        (Select Users) <.. (Notify Users) : <<extends>>
        (Select Users) <.. (Notify Sectional Heads) : <<extends>>

        (Notify Principals) -- PR

        A -- (View User Information )
        (View User Information ) <.. (Add User) : <<extends>>
        (View User Information ) <.. (Update User) : <<extends>>
        (View User Information ) <.. (Delete User) : <<extends>>

        (Add User) ..> (Update User Logs) : <<include>>
        (Update User) ..> (Update User Logs) : <<include>>
        (Delete User) ..> (Update User Logs) : <<include>>

        A -- (View System Monitor)
        (View System Monitor) <.. (Generate User Engagement Reports) : <<extends>>
        (View System Monitor) <.. (Generate Performance Reports) : <<extends>>
        (View System Monitor) <.. (Generate System Utilization Reports) : <<extends>>
        (View System Monitor) <.. (Generate Content Popularity Reports) : <<extends>>
        (View System Monitor) <.. (Generate Monthly Attendance Reports) : <<extends>>

        (Generate User Engagement Reports) ..> (Notify Principals) : <<include>>
        (Generate Performance Reports) ..> (Notify Principals) : <<include>>
        (Generate System Utilization Reports) ..> (Notify Principals) : <<include>>
        (Generate Content Popularity Reports) ..> (Notify Principals) : <<include>>
        (Generate Monthly Attendance Reports) ..> (Notify Principals) : <<include>>
}

@enduml