@startuml School Management System

skinparam Linetype ortho
skinparam classAttributeIconSize 0
hide circle

class User {
  # userType
  # userID
  # username
  # password
  # email
  # firstName
  # lastName
  # dateOfBirth
  # fingerprint
  # enterAttendance()
  # login()
  # viewProfile()
  # updateProfile()
  # logout()
}

class Student {
  - studentID
  - gradeLevel
  - studentReport
  - getStudentID()
  - getGradeLevel()
  - setGradeLevel()
  - getReport()
  - createReport()
  - updateReport()
}

class Teacher {
  # teacherID
  # getTeacherID()
  # getSubjectTaught()
  # setSubjectTaught()
  # getClassTaught()
  # setClassTaught()
  # updateClass()
  # viewStudentReport()
  # updateStudentReport()
  # viewStudentLetters()
  # informVicePrincipal()
  # informSectionalHead()
}

class SectionalHead {
  - section
  - getSection()
  - setSection()
  - informTeachers()
  - informStudents()
  - viewStudents()
  - addStudents()
  - updateStudents()
  - deleteStudents()
  - createClass()
  - deleteClass()
}

class VicePrincipal {
  # role
  # principalGrade
  # informPrincipal()
  # viewTeachers()
  # addTeachers()
  # updateTeachers()
  # deleteTeachers()
  # informSectionalHead()
  # viewEvents()
  # createEvents()
  # deleteEvents()
}

class Principal {
  # broadcastAnnouncements()
  # informUsers()
  # informVicePrincipals()
  # viewAdministrativeInformation()
  # viewFinancialInformation()
  # addPolicy()
  # deletePolicy()
}

class Admin {
  - adminLog
  - masterPassword
  - viewSystemDatabase()
  - createRecords()
  - editRecords()
  - deleteRecords()
  - viewUserInformation()
  - addUser()
  - updateUser()
  - deleteUser()
  - modifyPermissions()
  - viewSystemMonitor()
  - viewBackups()
  - regularInformationBackups()
  - generateSystemReports()
  - addUserLog()
  - updateUserLog()
  - deleteUserLog()
}

class Payment {
  - paymentId
  - amount
  - description
  - paymentDate
  - paymentMethod
  - status
  + paySchoolFees()
  + payWelfareFees()
  + donateSchool()
}

class SchoolFinanceDashboard {
  - schoolBudget
  - income
  - expense
  - donations
  - studentPayments
  + viewFinancialInformation()
}

class EducationalDashboard {
  + viewSocieties()
  + applyForSociety()
  + createSociety()
  + deleteSociety()
  + viewSubjects()
  + viewSubjectContent()
  + viewAssessments()
  + submitAssessment()
  + gradeAssessment()
  + createAssessment()
  + updateAssessment()
  + deleteAssessment()
  + viewCompetitions()
  + applyForCompetition()
  + createCompetition()
  + deleteCompetition()
}

class ExtracurricularDashboard {
  + viewContent()
  + viewClubs()
  + applyForClub()
  + createClub()
  + deleteClub()
  + viewCompetitions()
  + applyForCompetition()
  + createCompetition()
  + deleteCompetition()
}

class ExamInformation {
  + viewExams()
  + createExam()
  + updateExam()
  + deleteExam()
  + enterExamResults()
  + deleteExamResults()
  + applyForRecorrection()
  + enterExamResult()
  + changeExamResult()
  + deleteExamResult()
}

class Assessment {
  - id
  - title
  - description
  - dueDate
  - maxPoints
  - studentSubmissions
  - grade
  + submitSubmission()
  + updateSubmission()
  + removeSubmission()
}

class Exam {
  - id
  - name
  - description
  - date
  - duration
  - results
  + viewExam()
  + updateExam()
  + getResults()
}

class Result {
  - score
  - grade
  + getScore()
  + getGrade()
}

class Submission {
  - content
  - submissionDate
  + editSubmission()
}

class Grade {
  + createClasses()
  + deleteClasses()
  + addStudents()
  + removeStudents()
  + addTeachers()
  + removeTeachers()
}

class Subject {
  - subjectName
  - subjectContent
  - creditPoints
  - hours
  + addContent()
  + removeContent()
}

class Class {
  - classMonitor
  - studentCount
  - timeTable
  + addClassMonitor()
  + removeClassMonitor()
}

class StudentReport {
  - dateCreated
  - dateModified
  - generatedBy
  - studentPerformance
  - studentAttendance
  - studentLetters
  - studentAchievements
  - studentHealthStatus
  + updateStudentReport()
  + viewStudentReport()
}

User <|-- Student
User <|-- Teacher
User <|-- VicePrincipal
Teacher <|-- SectionalHead
VicePrincipal <|-- Principal
VicePrincipal -- Event
Principal <|-- Admin

Grade "1" *-- "1..*" Class : Has
Grade "1" -- "1..*" Teacher : Has
Grade "1" -- "1" SectionalHead : Has
Grade "1" *-- "1..*" Subject : Has
Class "1" -- "1..*" Student : Has
Admin "1" -- "1" SystemLog : View
Principal "1" -- "1" VicePrincipal : Inform
Principal "1" -- "0..*" Announcement : Manage
VicePrincipal "1" -- "1" SchoolFinanceDashboard : Manage
VicePrincipal "1" -- "1..*" Teacher : Manage
SectionalHead "1" -- "1" Grade : Manage
SectionalHead "1*" -- "1..*" Student : Manage
SectionalHead "1*" -- "1..*" Teacher : Inform
Teacher "1" -- "0..1" Class : Manage
Teacher "1" -- "1" ExtracurricularDashboard : Manage
Teacher "1" -- "1" EducationalDashboard : Manage
Teacher "1" -- "0..*" Request : Manage
Teacher "1" -- "1..*" Subject : Manage
Teacher "1" -- "0..*" StudentReport : Manage
Student "1" -- "1" EducationalDashboard : View
Student "1" -- "1" ExtracurricularDashboard : View
Student "1" -- "0..*" Request : Submit
Student "1" -- "0..*" Payment : Make
User "1" -- "0..*" Event : View
User "1" -- "0..*" Announcement : View

SchoolFinanceDashboard "1" o-- "0..*" Payment : Has
EducationalDashboard "1" o-- "0..*" ExamInformation : Has
EducationalDashboard "1" o-- "0..*" Assessment : Has
EducationalDashboard "1" o-- "0..*" Subject : Has
ExamInformation "1" o-- "0..*" Exam : Has
Exam "1" O--- "0..*" Result : Has
Assessment "1" o-- "0..*" Submission : Has
Student "1" *-- "1" StudentReport : Has


@enduml