@startuml School Management System

actor Student
boundary "School Management System" as SchoolManagementSystem
control Payment
entity Finance

Student -> SchoolManagementSystem: View Payment Information
activate SchoolManagementSystem
SchoolManagementSystem --> Student: Display payment information
SchoolManagementSystem -> Payment: Pay School Fees
activate Payment
Payment --> Student: Confirmation Message
Student -> Payment: Confirmation
Payment -> Finance: Update Payment Information
activate Finance
Finance --> Payment: Payment Information Updated
deactivate Finance
Payment --> Student: Payment Complete
deactivate Payment

SchoolManagementSystem -> Payment: Pay Welfare Fees
activate Payment
Payment --> Student: Confirmation Message
Student -> Payment: Confirmation
Payment -> Finance: Update Payment Information
activate Finance
Finance --> Payment: Payment Information Updated
deactivate Finance
Payment --> Student: Payment Complete
deactivate Payment

SchoolManagementSystem -> Payment: Donate to the School
activate Payment
Payment --> Student: Confirmation Message
Student -> Payment: Confirmation
Payment -> Finance: Update Payment Information
activate Finance
Finance --> Payment: Payment Information Updated
deactivate Finance
Payment --> Student: Payment Complete
deactivate Payment

@enduml