@startuml School Management System

left to right direction
skinparam linetype polyline

actor "User" as U
actor "User" as UR
actor "Student" as S
actor "Student" as SR
actor "Teacher" as T
actor "Teacher" as TR
actor "Sectional Head" as SH
actor "Sectional Head" as SHR
actor "Principal" as P
actor "Principal" as PR
actor "Administrator" as A

U <|-- S
U <|-- T
T <|-- SH
SH <|-- P
P <|-- A

rectangle "School Management System" {
        U -- (Enter the Attendance Daily)
        (Enter the Attendance Daily) ..> (Verify Using Fingerprint) : <<include>>
        (Verify Using Fingerprint) ..> (Update User Log) : <<include>>

        U -- (Login)
        (Login) ..> (Validate User) : <<include>>
        (Validate User) ..> (Update User Log) : <<include>>

        U -- (View User Profile)
        (View User Profile) <.. (Update User Profile) : <<extends>>
        (Update User Profile) ..> (Update User Log) : <<include>>

        U -- (Comminication)
        (Comminication) <.. (Send Messages) : <<extends>>
        (Send Messages) ..> (Update User Log) : <<include>>

        U -- (Logout)
        (Logout) ..> (Confirm) : <<include>>
        (Confirm) ..> (Update User Log) : <<include>>

        (Notify Users) -- UR

        S -- (View Educational Information)
        (View Educational Information) <.. (Submit Assessments) : <<extends>>

        (Submit Assessments) ..> (Update Educational Information) : <<include>>

        S -- (View Exams Information)
        (View Exams Information) <.. (View Exams) : <<extends>>
        (View Exams Information) <.. (View Exam Results) : <<extends>>
        (View Exam Results) <.. (Apply for Recorrections) : <<extends>>
        (View Exam Results) <.. (Calculate GPA) : <<extends>>

        (Update Student Informations) -- SR
        (Update Educational Informations) -- SR
        (Update Exam Informations) -- SR

        T -- (View Student Informations)
        (View Student Informations) <.. (Create Student Informations) : <<extends>>
        (View Student Informations) <.. (Delete Student Informations) : <<extends>>
        (View Student Informations) <.. (Generate Student Attendance Reports) : <<extends>>
        (View Student Informations) <.. (Generate Student Performance Reports) : <<extends>>
        (View Student Informations) <.. (Generate Enrollment Reports) : <<extends>>

        (Create Student Informations) ..> (Update Student Informations) : <<include>>
        (Delete Student Informations) ..> (Update Student Informations) : <<include>>
        (Generate Student Attendance Reports) ..> (Update Student Informations) : <<include>>
        (Generate Student Performance Reports) ..> (Update Student Informations) : <<include>>
        (Generate Enrollment Reports) ..> (Update Student Informations): <<include>>

        T -- (View Educational Informations)
        (View Educational Informations) <.. (Create Assessments) : <<extends>>
        (View Educational Informations) <.. (Edit Assessments) : <<extends>>
        (View Educational Informations) <.. (Delete Assessments) : <<extends>>
        (View Educational Informations) <.. (View Student Submissions) : <<extends>>
        (View Educational Informations) <.. (Grade Student Submissions) : <<extends>>

        (Create Assessments) ..> (Update Educational Informations): <<include>>
        (Edit Assessments) ..> (Update Educational Informations): <<include>>
        (Delete Assessments) ..> (Update Educational Informations): <<include>>
        (Grade Student Submissions) ..> (Update Educational Informations) : <<include>>

        T -- (View Exam Informations)
        (View Exam Informations) <.. (Create Exams) : <<extends>>
        (View Exam Informations) <.. (Update Exams) : <<extends>>
        (View Exam Informations) <.. (Delete Exams) : <<extends>>
        (View Exam Informations) <.. (Edit Exam Results) : <<extends>>

        (Create Exams) ..> (Update Exam Informations) : <<include>>
        (Update Exams) ..> (Update Exam Informations) : <<include>>
        (Delete Exams) ..> (Update Exam Informations) : <<include>>
        (Edit Exam Results) ..> (Update Exam Informations) : <<include>>

        (Update Educational Information) -- TR
        (Apply for Recorrections) -- TR
        (Notify Teachers) -- TR

        SH -- (View Staff Informations)
        (View Staff Informations) <.. (Add Staff Members) : <<extends>>
        (View Staff Informations) <.. (Update Staff Members) : <<extends>>
        (View Staff Informations) <.. (Remove Staff Members) : <<extends>>
        
        SH -- (View Sectional Informations)
        (View Sectional Informations) <.. (Create Time Tables) : <<extends>>
        (View Sectional Informations) <.. (Update Time Tables) : <<extends>>
        (View Sectional Informations) <.. (Delete Time Tables) : <<extends>>

        (Notify Sectional Heads) -- SHR

        (Add Staff Members) ..> (Notify Teachers) : <<include>>
        (Update Staff Members) ..> (Notify Teachers) : <<include>>
        (Remove Staff Members) ..> (Notify Teachers) : <<include>>
        (Create Time Tables) ..> (Notify Teachers): <<include>>
        (Update Time Tables) ..> (Notify Teachers) : <<include>>
        (Delete Time Tables) ..> (Notify Teachers) : <<include>>

        P -- (Broadcast Announcements)
        (Broadcast Announcements) ..> (Select Users) : <<include>>

        (Select Users) <.. (Notify Users) : <<extends>>
        (Select Users) <.. (Notify Sectional Heads) : <<extends>>

        (Notify Principals) -- PR

        A -- (View User Informations)
        (View User Informations) <.. (Add User) : <<extends>>
        (View User Informations) <.. (Update User) : <<extends>>
        (View User Informations) <.. (Delete User) : <<extends>>

        (Add User) ..> (Update User Logs) : <<include>>
        (Update User) ..> (Update User Logs) : <<include>>
        (Delete User) ..> (Update User Logs) : <<include>>

        A -- (View System Monitor)
        (View System Monitor) <.. (Generate User Engagement Reports) : <<extends>>
        (View System Monitor) <.. (Generate Performance Reports) : <<extends>>
        (View System Monitor) <.. (Generate System Utilization Reports) : <<extends>>
        (View System Monitor) <.. (Generate Content Popularity Reports) : <<extends>>
        (View System Monitor) <.. (Generate Monthly Attendance Reports) : <<extends>>

        (Generate User Engagement Reports) ..> (Notify Principals) : <<include>>
        (Generate Performance Reports) ..> (Notify Principals) : <<include>>
        (Generate System Utilization Reports) ..> (Notify Principals) : <<include>>
        (Generate Content Popularity Reports) ..> (Notify Principals) : <<include>>
        (Generate Monthly Attendance Reports) ..> (Notify Principals) : <<include>>
}

@enduml